### ISSUE TITLE
after running both setups

### ISSUE THREAD

**Issue by SDaany** [JJGO/dotfiles#2]
bash: /home/jun/.config/broot/launcher/bash/br: No such file or directory
bash: /Users/josejavier/Library/Preferences/org.dystroy.broot/launcher/bash/br: No such file or directory

**Comment by JJGO** [comment]
Remove the appropriate lines from `.env` and `.bashrc` and the warnings should go away. I'm closing the issue since this repo is for my setup and I don't intend for this to work out of the box for others.
