### ISSUE TITLE
I am trying to get your terminal setup like the one from Lecture 2 of "The Missing Semester"

### ISSUE THREAD

**Issue by mriganktiwari** [JJGO/dotfiles#3]
<img width="565" alt="image" src="https://user-images.githubusercontent.com/21966929/184055451-a16d8865-24f3-4d82-95a2-21fe7ff47621.png">

Something like this, but executing the scripts in this repo aren't helping.
Could you please guide me?

**Comment by haxfn** [comment]
Hi, I understand that you want to copy the config, use GNU Stow.

https://www.youtube.com/results?search_query=copy+config+with+gnu+stow

Keep in mind that that many things may break.

**Comment by JJGO** [comment]
You want to install sorin's theme from https://github.com/sorin-ionescu/prezto

This is the script I use to bootstrap zprezto before applying stow: https://github.com/JJGO/dotfiles/blob/master/shell-setup.sh#L52
